import js from '@eslint/js';

const browserGlobals = {
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  Audio: 'readonly',
  Blob: 'readonly',
  Buffer: 'readonly',
  CSS: 'readonly',
  RTCPeerConnection: 'readonly',
  CustomEvent: 'readonly',
  DataTransfer: 'readonly',
  Element: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  FormData: 'readonly',
  Headers: 'readonly',
  HTMLElement: 'readonly',
  Image: 'readonly',
  IntersectionObserver: 'readonly',
  KeyboardEvent: 'readonly',
  MediaRecorder: 'readonly',
  MutationObserver: 'readonly',
  Node: 'readonly',
  Notification: 'readonly',
  PointerEvent: 'readonly',
  ReadableStream: 'readonly',
  ResizeObserver: 'readonly',
  Response: 'readonly',
  SVGElement: 'readonly',
  TextDecoder: 'readonly',
  TextEncoder: 'readonly',
  SpeechSynthesisUtterance: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  WebSocket: 'readonly',
  afterAll: 'readonly',
  afterEach: 'readonly',
  alert: 'readonly',
  atob: 'readonly',
  beforeAll: 'readonly',
  beforeEach: 'readonly',
  btoa: 'readonly',
  clearInterval: 'readonly',
  clearTimeout: 'readonly',
  cancelAnimationFrame: 'readonly',
  confirm: 'readonly',
  console: 'readonly',
  crypto: 'readonly',
  describe: 'readonly',
  document: 'readonly',
  expect: 'readonly',
  fetch: 'readonly',
  global: 'readonly',
  history: 'readonly',
  it: 'readonly',
  location: 'readonly',
  localStorage: 'readonly',
  matchMedia: 'readonly',
  navigator: 'readonly',
  performance: 'readonly',
  process: 'readonly',
  requestAnimationFrame: 'readonly',
  sessionStorage: 'readonly',
  setInterval: 'readonly',
  setTimeout: 'readonly',
  test: 'readonly',
  vi: 'readonly',
  window: 'readonly',
  XMLHttpRequest: 'readonly',
};

export default [
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      'coverage/**',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.js', '**/*.jsx', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: browserGlobals,
    },
    rules: {
      'no-control-regex': 'off',
      'no-unused-vars': 'off',
      'no-undef': 'error',
    },
  },
];
