import { hasConfiguredEnvValue } from '../env.js';

export const LINKEDIN_VERSION = '202603';
export const DEFAULT_LINKEDIN_SCOPES = ['openid', 'profile', 'email', 'w_member_social'];
const LINKEDIN_AUTH_URL = 'https://www.linkedin.com/oauth/v2/authorization';
const LINKEDIN_TOKEN_URL = 'https://www.linkedin.com/oauth/v2/accessToken';
const MICROSOFT_AUTH_URL = 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize';
const MICROSOFT_TOKEN_URL = 'https://login.microsoftonline.com/common/oauth2/v2.0/token';

export function parseLinkedInScopes() {
  return String(process.env.LINKEDIN_SCOPES || '')
    .split(/[,\s]+/)
    .map((scope) => scope.trim())
    .filter(Boolean);
}

/** Shared manual webhook fields (endpoint + optional auth style). */
const STANDARD_WEBHOOK_FIELDS = [
  {
    key: 'endpointUrl',
    label: 'Webhook URL',
    placeholder: 'https://hooks.example.com/endpoint',
    requiredOnConnect: true,
    helpText: 'Use HTTPS. Paste the full incoming webhook or automation URL from your provider.',
  },
  {
    key: 'method',
    label: 'HTTP method',
    input: 'select',
    options: ['POST', 'PUT'],
  },
  {
    key: 'authHeaderName',
    label: 'Auth header name',
    placeholder: 'Authorization',
  },
  {
    key: 'authScheme',
    label: 'Auth scheme',
    input: 'select',
    options: ['Bearer', 'Token', 'Raw'],
  },
];

const TEXT_HOOK_FIELDS = [
  {
    key: 'endpointUrl',
    label: 'Incoming webhook URL',
    placeholder: 'https://hooks.slack.com/...',
    requiredOnConnect: true,
    helpText: 'Paste the service-provided incoming webhook URL. Optional bearer token in the secret field if required.',
  },
];

export const INTEGRATION_DEFINITIONS = {
  gmail: {
    name: 'Gmail',
    section: 'emails',
    category: 'Email',
    color: '#EA4335',
    icon: 'GM',
    description: 'Connect Gmail via Google OAuth so agents can use real inbox context and send mail from your linked account.',
    authMode: 'oauth',
    capabilities: ['inbox_context', 'send_email'],
    supportsPublish: false,
    settingsFields: [],
    sortOrder: 10,
    authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenUrl: 'https://oauth2.googleapis.com/token',
    scopes: ['https://mail.google.com/', 'https://www.googleapis.com/auth/gmail.send'],
    clientId: () => process.env.GOOGLE_CLIENT_ID,
    clientSecret: () => process.env.GOOGLE_CLIENT_SECRET,
    supportsRefresh: true,
  },
  outlook: {
    name: 'Outlook',
    section: 'emails',
    category: 'Email',
    color: '#0078D4',
    icon: 'OL',
    description: 'Connect Microsoft 365 via OAuth so Prymal can verify the mailbox and send outbound email from that identity.',
    authMode: 'oauth',
    capabilities: ['inbox_context', 'send_email', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Recipient email(s)',
    settingsFields: [
      {
        key: 'defaultRecipientEmail',
        label: 'Default recipient email(s)',
        placeholder: 'founder@example.com',
        helpText: 'Use commas to separate multiple recipients for quick send tests.',
      },
    ],
    sortOrder: 15,
    authUrl: MICROSOFT_AUTH_URL,
    tokenUrl: MICROSOFT_TOKEN_URL,
    scopes: ['openid', 'profile', 'email', 'offline_access', 'User.Read', 'Mail.Send'],
    clientId: () => process.env.MICROSOFT_CLIENT_ID,
    clientSecret: () => process.env.MICROSOFT_CLIENT_SECRET,
    supportsRefresh: true,
  },
  google_drive: {
    name: 'Google Drive',
    section: 'files',
    category: 'Storage',
    color: '#34A853',
    icon: 'GD',
    description: 'Link Google Drive through OAuth so file-aware workflows can trust documents from your account.',
    authMode: 'oauth',
    capabilities: ['file_account_link', 'storage_access'],
    supportsPublish: false,
    settingsFields: [],
    sortOrder: 20,
    authUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
    tokenUrl: 'https://oauth2.googleapis.com/token',
    scopes: ['https://www.googleapis.com/auth/drive.readonly'],
    clientId: () => process.env.GOOGLE_CLIENT_ID,
    clientSecret: () => process.env.GOOGLE_CLIENT_SECRET,
    supportsRefresh: true,
  },
  onedrive: {
    name: 'OneDrive',
    section: 'files',
    category: 'Files',
    color: '#0A5BD3',
    icon: 'OD',
    description: 'Connect OneDrive via Microsoft OAuth and pin a trusted file account to this organisation.',
    authMode: 'oauth',
    capabilities: ['file_account_link', 'storage_access'],
    supportsPublish: false,
    settingsFields: [],
    sortOrder: 25,
    authUrl: MICROSOFT_AUTH_URL,
    tokenUrl: MICROSOFT_TOKEN_URL,
    scopes: ['openid', 'profile', 'email', 'offline_access', 'User.Read', 'Files.Read.All'],
    clientId: () => process.env.MICROSOFT_CLIENT_ID,
    clientSecret: () => process.env.MICROSOFT_CLIENT_SECRET,
    supportsRefresh: true,
  },
  dropbox: {
    name: 'Dropbox',
    section: 'files',
    category: 'Files',
    color: '#0061FF',
    icon: 'DB',
    description: 'Paste a Dropbox user access token so Prymal can verify the workspace user and scope storage correctly.',
    authMode: 'manual_token',
    secretLabel: 'Dropbox access token',
    secretPlaceholder: 'Dropbox access token',
    capabilities: ['file_account_link', 'storage_access'],
    supportsPublish: false,
    settingsFields: [],
    sortOrder: 27,
  },
  box: {
    name: 'Box',
    section: 'files',
    category: 'Files',
    color: '#0A66FF',
    icon: 'BX',
    description: 'Verify Box with a user access token and keep that storage source explicit for downstream file workflows.',
    authMode: 'manual_token',
    secretLabel: 'Box access token',
    secretPlaceholder: 'Box access token',
    capabilities: ['file_account_link', 'storage_access'],
    supportsPublish: false,
    settingsFields: [],
    sortOrder: 29,
  },
  notion: {
    name: 'Notion',
    section: 'knowledge',
    category: 'Knowledge',
    color: '#111827',
    icon: 'NO',
    description: 'Authorize Notion OAuth to attach a workspace for notes, databases, and knowledge-aware agents.',
    authMode: 'oauth',
    capabilities: ['workspace_account_link', 'knowledge_account'],
    supportsPublish: false,
    settingsFields: [],
    sortOrder: 30,
    authUrl: 'https://api.notion.com/v1/oauth/authorize',
    tokenUrl: 'https://api.notion.com/v1/oauth/token',
    scopes: [],
    clientId: () => process.env.NOTION_CLIENT_ID,
    clientSecret: () => process.env.NOTION_CLIENT_SECRET,
    supportsRefresh: false,
  },
  slack: {
    name: 'Slack',
    section: 'messaging',
    category: 'Communication',
    color: '#4A154B',
    icon: 'SL',
    description: 'Install the Slack app with OAuth, then post workflow alerts and handoffs into channels using channel IDs.',
    authMode: 'oauth',
    capabilities: ['team_handoffs', 'workflow_alerts', 'autopost'],
    supportsPublish: true,
    targetLabel: 'Channel ID or App Home user ID',
    settingsFields: [
      {
        key: 'defaultChannelId',
        label: 'Default channel ID',
        placeholder: 'C0123456789',
        helpText: 'Used for workflow alerts and test posts when you do not override the target.',
      },
    ],
    sortOrder: 40,
    authUrl: 'https://slack.com/oauth/v2/authorize',
    tokenUrl: 'https://slack.com/api/oauth.v2.access',
    scopes: ['chat:write', 'channels:read'],
    clientId: () => process.env.SLACK_CLIENT_ID,
    clientSecret: () => process.env.SLACK_CLIENT_SECRET,
    supportsRefresh: false,
  },
  discord: {
    name: 'Discord',
    section: 'socials',
    category: 'Community',
    color: '#5865F2',
    icon: 'DC',
    description: 'Add a bot token and default channel ID to push launch notes, community updates, and operator alerts.',
    authMode: 'manual_token',
    secretLabel: 'Bot token',
    secretPlaceholder: 'Discord bot token',
    capabilities: ['community_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Channel ID',
    settingsFields: [
      {
        key: 'defaultChannelId',
        label: 'Default channel ID',
        placeholder: '123456789012345678',
        requiredOnConnect: true,
      },
    ],
    sortOrder: 50,
  },
  telegram: {
    name: 'Telegram',
    section: 'messaging',
    category: 'Messaging',
    color: '#229ED9',
    icon: 'TG',
    description: 'Register a bot token and target chat ID to broadcast text and image drops to groups or channels.',
    authMode: 'manual_token',
    secretLabel: 'Bot token',
    secretPlaceholder: 'Telegram bot token',
    capabilities: ['broadcasts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    supportsImagePublish: true,
    targetLabel: 'Chat ID or @channelusername',
    settingsFields: [
      {
        key: 'defaultChatId',
        label: 'Default chat ID or channel',
        placeholder: '@prymal_updates',
        requiredOnConnect: true,
      },
    ],
    sortOrder: 60,
  },
  x: {
    name: 'X',
    section: 'socials',
    category: 'Social',
    color: '#111111',
    icon: 'X',
    description: 'Use an X user access token to publish short posts and threads from the workspace publish panel.',
    authMode: 'manual_token',
    secretLabel: 'X OAuth 2.0 user access token',
    secretPlaceholder: 'Bearer token with tweet.write permission',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [],
    sortOrder: 70,
  },
  mastodon: {
    name: 'Mastodon',
    section: 'socials',
    category: 'Social',
    color: '#563ACC',
    icon: 'MD',
    description: 'Pair a user token with your instance base URL to post with the visibility level you choose.',
    authMode: 'manual_token',
    secretLabel: 'Mastodon user access token',
    secretPlaceholder: 'Mastodon token with write:statuses scope',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [
      {
        key: 'instanceUrl',
        label: 'Instance URL',
        placeholder: 'https://mastodon.social',
        requiredOnConnect: true,
        helpText: 'Use the full base URL for the account instance.',
      },
      {
        key: 'defaultVisibility',
        label: 'Default visibility',
        input: 'select',
        options: ['public', 'unlisted', 'private'],
      },
    ],
    sortOrder: 75,
  },
  linkedin: {
    name: 'LinkedIn',
    section: 'socials',
    category: 'Social',
    color: '#0A66C2',
    icon: 'LI',
    description: 'Connect LinkedIn with OAuth, choose a member or company author, and publish approved text or link updates.',
    authMode: 'oauth',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Author URN',
    settingsFields: [
      {
        key: 'authorUrn',
        label: 'Author URN',
        placeholder: 'urn:li:organization:123456',
        helpText: 'Use urn:li:person:<id> for personal posting or urn:li:organization:<id> for company posting. The connected LinkedIn account must have permission to post as this author.',
      },
      {
        key: 'selectedOrganizationUrn',
        label: 'Selected organisation URN',
        placeholder: 'urn:li:organization:123456',
        helpText: 'Optional derived value used when an available LinkedIn organisation author is selected.',
      },
      {
        key: 'selectedOrganizationName',
        label: 'Selected organisation name',
        placeholder: 'Company name',
        helpText: 'Optional display label for the selected LinkedIn organisation author.',
      },
      {
        key: 'defaultVisibility',
        label: 'Default visibility',
        input: 'select',
        options: ['PUBLIC', 'CONNECTIONS'],
      },
    ],
    defaultHeaders: {
      'X-Restli-Protocol-Version': '2.0.0',
      'Linkedin-Version': LINKEDIN_VERSION,
    },
    authUrl: LINKEDIN_AUTH_URL,
    tokenUrl: LINKEDIN_TOKEN_URL,
    scopes: parseLinkedInScopes().length ? parseLinkedInScopes() : DEFAULT_LINKEDIN_SCOPES,
    clientId: () => process.env.LINKEDIN_CLIENT_ID,
    clientSecret: () => process.env.LINKEDIN_CLIENT_SECRET,
    supportsRefresh: true,
    sortOrder: 80,
  },
  bluesky: {
    name: 'Bluesky',
    section: 'socials',
    category: 'Social',
    color: '#1185FE',
    icon: 'BS',
    description: 'Sign in with your handle and an app password to publish Bluesky posts over the AT Protocol.',
    authMode: 'manual_token',
    secretLabel: 'App password',
    secretPlaceholder: 'Bluesky app password',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [
      {
        key: 'blueskyIdentifier',
        label: 'Bluesky handle or DID',
        placeholder: 'you.bsky.social',
        requiredOnConnect: true,
        helpText: 'Use your full handle (example.bsky.social) or DID.',
      },
    ],
    integrationRuntime: 'bluesky',
    sortOrder: 81,
  },
  github_social: {
    name: 'GitHub',
    section: 'socials',
    category: 'Dev social',
    color: '#24292F',
    icon: 'GH',
    description: 'Verify a GitHub PAT and publish shareable snippets as private Gists when you run a live post.',
    authMode: 'manual_token',
    secretLabel: 'GitHub personal access token',
    secretPlaceholder: 'GitHub fine-grained or classic PAT',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    integrationRuntime: 'github_social',
    sortOrder: 82,
  },
  social_zapier: {
    name: 'Zapier Webhooks',
    section: 'socials',
    category: 'Automation',
    color: '#FF4A00',
    icon: 'ZP',
    description: 'Forward Prymal payloads to a Zapier Catch Hook URL so Zaps can cross-post and enrich CRM data.',
    authMode: 'manual_token',
    secretLabel: 'Shared secret (optional)',
    secretPlaceholder: 'Bearer token if your hook requires it',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Zapier hook URL',
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 83,
  },
  social_make: {
    name: 'Make (Integromat)',
    section: 'socials',
    category: 'Automation',
    color: '#6D4AFF',
    icon: 'MK',
    description: 'POST to a Make custom webhook so scenarios can route drops to Instagram, Facebook Pages, and more.',
    authMode: 'manual_token',
    secretLabel: 'Bearer token (optional)',
    secretPlaceholder: 'Optional Make webhook auth',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 84,
  },
  social_ifttt: {
    name: 'IFTTT Webhooks',
    section: 'socials',
    category: 'Automation',
    color: '#000000',
    icon: 'IF',
    description: 'Trigger IFTTT Webhooks applets to archive or cross-post when you cannot use native OAuth here.',
    authMode: 'manual_token',
    secretLabel: 'Webhook key segment (optional)',
    secretPlaceholder: 'Often embedded in the URL; add bearer here only if needed',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 85,
  },
  social_n8n: {
    name: 'n8n',
    section: 'socials',
    category: 'Automation',
    color: '#EA4B71',
    icon: 'N8',
    description: 'Hit an n8n webhook entrypoint to execute self-hosted or cloud workflows on every payload.',
    authMode: 'manual_token',
    secretLabel: 'Auth header (optional)',
    secretPlaceholder: 'Optional webhook auth',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 86,
  },
  social_pipedream: {
    name: 'Pipedream',
    section: 'socials',
    category: 'Automation',
    color: '#208080',
    icon: 'PD',
    description: 'Stream events into a Pipedream HTTP source for retries, code steps, and multi-branch routing.',
    authMode: 'manual_token',
    secretLabel: 'Bearer token (optional)',
    secretPlaceholder: 'Pipedream custom auth',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 87,
  },
  social_hookdeck: {
    name: 'Hookdeck',
    section: 'socials',
    category: 'Automation',
    color: '#5C6BF2',
    icon: 'HD',
    description: 'Send traffic through Hookdeck to replay, filter, and throttle events before downstream tools.',
    authMode: 'manual_token',
    secretLabel: 'Verification secret (optional)',
    secretPlaceholder: 'If Hookdeck or downstream validates bearer secrets',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 88,
  },
  social_svix: {
    name: 'Svix',
    section: 'socials',
    category: 'Automation',
    color: '#FF5F57',
    icon: 'SV',
    description: 'Emit webhook-shaped payloads to consumers that expect a Svix-style event ingestion endpoint.',
    authMode: 'manual_token',
    secretLabel: 'Endpoint signing secret (optional)',
    secretPlaceholder: 'If your consumer expects an Authorization bearer',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 89,
  },
  social_paragon: {
    name: 'Paragon',
    section: 'socials',
    category: 'Automation',
    color: '#7B61FF',
    icon: 'PG',
    description: 'Call your Paragon Connect ingress URL to sync outbound posts with CRM, ads, and SaaS systems.',
    authMode: 'manual_token',
    secretLabel: 'Webhook secret (optional)',
    secretPlaceholder: 'Bearer if required by your Paragon ingress',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 90,
  },
  social_tray: {
    name: 'Tray.io',
    section: 'socials',
    category: 'Automation',
    color: '#6C3DFF',
    icon: 'TY',
    description: 'Target Tray.io callable URLs to wire social output into enterprise automation recipes.',
    authMode: 'manual_token',
    secretLabel: 'Tray auth (optional)',
    secretPlaceholder: 'Bearer token if your Tray webhook requires it',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 91,
  },
  social_workato: {
    name: 'Workato',
    section: 'socials',
    category: 'Automation',
    color: '#25C16F',
    icon: 'WA',
    description: 'POST to Workato listeners to orchestrate GTM, lifecycle, and ad-platform recipes.',
    authMode: 'manual_token',
    secretLabel: 'Listener secret (optional)',
    secretPlaceholder: 'Bearer token if configured',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 92,
  },
  social_generic_bridge: {
    name: 'HTTP bridge (social)',
    section: 'socials',
    category: 'Custom',
    color: '#64748B',
    icon: 'HB',
    description: 'POST JSON to any HTTPS endpoint you control for bespoke scripting or internal tooling.',
    authMode: 'manual_token',
    secretLabel: 'Bearer token (optional)',
    secretPlaceholder: 'Optional bearer for your endpoint',
    capabilities: ['social_posts', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 93,
  },
  line_messaging: {
    name: 'LINE Official',
    section: 'messaging',
    category: 'Messaging',
    color: '#00B900',
    icon: 'LN',
    description: 'Verify a LINE Messaging API channel token, then push to a recipient user ID (UID) you specify.',
    authMode: 'manual_token',
    secretLabel: 'Channel access token',
    secretPlaceholder: 'LINE channel access token',
    capabilities: ['autopost', 'delivery_feedback', 'team_handoffs'],
    supportsPublish: true,
    targetLabel: 'LINE user ID (UID)',
    settingsFields: [
      {
        key: 'defaultChatId',
        label: 'Default LINE user ID',
        placeholder: 'Uxxxxxxxx…',
        requiredOnConnect: true,
        helpText: 'Use the recipient UID from LINE Developers console / webhook payloads.',
      },
    ],
    integrationRuntime: 'line_channel',
    sortOrder: 61,
  },
  mattermost_incoming: {
    name: 'Mattermost',
    section: 'messaging',
    category: 'Messaging',
    color: '#0072C6',
    icon: 'MM',
    description: 'Use a Mattermost incoming webhook URL; Prymal posts compact JSON with a text field to the channel.',
    authMode: 'manual_token',
    secretLabel: 'Webhook secret (optional)',
    secretPlaceholder: 'Some Mattermost hooks allow bearer tokens',
    capabilities: ['workflow_alerts', 'autopost'],
    supportsPublish: true,
    settingsFields: [...TEXT_HOOK_FIELDS],
    integrationRuntime: 'text_hook',
    sortOrder: 62,
  },
  google_chat_incoming: {
    name: 'Google Chat',
    section: 'messaging',
    category: 'Messaging',
    color: '#34A853',
    icon: 'GC',
    description: 'Use a Google Chat incoming webhook URL so messages land as space notifications your team already watches.',
    authMode: 'manual_token',
    secretLabel: 'Token (optional)',
    secretPlaceholder: 'Usually unused for Chat webhooks',
    capabilities: ['workflow_alerts', 'autopost'],
    supportsPublish: true,
    settingsFields: [...TEXT_HOOK_FIELDS],
    integrationRuntime: 'text_hook',
    sortOrder: 63,
  },
  teams_incoming: {
    name: 'Microsoft Teams',
    section: 'messaging',
    category: 'Messaging',
    color: '#6264A7',
    icon: 'TM',
    description: 'Paste a Teams incoming webhook URL; Prymal delivers simple text payloads to that channel feed.',
    authMode: 'manual_token',
    secretLabel: 'Secret (optional)',
    secretPlaceholder: 'Rarely needed for Teams incoming webhooks',
    capabilities: ['workflow_alerts', 'autopost'],
    supportsPublish: true,
    settingsFields: [...TEXT_HOOK_FIELDS],
    integrationRuntime: 'text_hook',
    sortOrder: 64,
  },
  rocket_chat_incoming: {
    name: 'Rocket.Chat',
    section: 'messaging',
    category: 'Messaging',
    color: '#F5455C',
    icon: 'RC',
    description: 'Connect a Rocket.Chat Incoming WebHook so team channels receive Prymal text updates.',
    authMode: 'manual_token',
    secretLabel: 'Token (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['workflow_alerts', 'autopost'],
    supportsPublish: true,
    settingsFields: [...TEXT_HOOK_FIELDS],
    integrationRuntime: 'text_hook',
    sortOrder: 65,
  },
  zulip_incoming: {
    name: 'Zulip',
    section: 'messaging',
    category: 'Messaging',
    color: '#6492F4',
    icon: 'ZU',
    description: 'Target a Zulip incoming webhook URL to post updates into the configured stream or topic.',
    authMode: 'manual_token',
    secretLabel: 'Bot token (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['workflow_alerts', 'autopost'],
    supportsPublish: true,
    settingsFields: [...TEXT_HOOK_FIELDS],
    integrationRuntime: 'text_hook',
    sortOrder: 66,
  },
  slack_incoming_webhook: {
    name: 'Slack Incoming Webhook',
    section: 'messaging',
    category: 'Messaging',
    color: '#ECB32D',
    icon: 'S+',
    description: 'Use Slack legacy incoming webhook URLs for URL-only posting without installing the OAuth app.',
    authMode: 'manual_token',
    secretLabel: 'Legacy secret (rare)',
    secretPlaceholder: 'Usually empty; URL embeds the secret',
    capabilities: ['workflow_alerts', 'autopost'],
    supportsPublish: true,
    settingsFields: [...TEXT_HOOK_FIELDS],
    integrationRuntime: 'text_hook',
    sortOrder: 67,
  },
  discord_incoming_webhook: {
    name: 'Discord Webhook (URL-only)',
    section: 'messaging',
    category: 'Messaging',
    color: '#99AAB5',
    icon: 'D+',
    description: 'Paste a Discord channel webhook URL for lightweight posts without a full bot install.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Rare for Discord; leave blank unless the hook requires a header',
    capabilities: ['workflow_alerts', 'autopost'],
    supportsPublish: true,
    settingsFields: [...TEXT_HOOK_FIELDS],
    integrationRuntime: 'discord_hook',
    sortOrder: 68,
  },
  guilded_webhook: {
    name: 'Guilded',
    section: 'messaging',
    category: 'Messaging',
    color: '#E4B12E',
    icon: 'GW',
    description: 'Use a Guilded server webhook URL; payloads mirror Discord-style messages for that server.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['community_posts', 'autopost'],
    supportsPublish: true,
    settingsFields: [...TEXT_HOOK_FIELDS],
    integrationRuntime: 'discord_hook',
    sortOrder: 69,
  },
  matrix_webhook_bridge: {
    name: 'Matrix bridge',
    section: 'messaging',
    category: 'Messaging',
    color: '#0DBD8B',
    icon: 'MX',
    description: 'Deliver JSON to your Matrix appservice, bridge, or automation URL with optional bearer auth.',
    authMode: 'manual_token',
    secretLabel: 'Bearer token (optional)',
    secretPlaceholder: 'Optional bridge auth',
    capabilities: ['workflow_alerts', 'autopost'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 70,
  },
  webex_incoming: {
    name: 'Webex',
    section: 'messaging',
    category: 'Messaging',
    color: '#00BCED',
    icon: 'WX',
    description: 'Point at a Webex messaging webhook to drop updates into a space that accepts JSON posts.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['workflow_alerts', 'autopost'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 71,
  },
  resend: {
    name: 'Resend',
    section: 'emails',
    category: 'Transactional',
    color: '#171717',
    icon: 'RS',
    description: 'Store a Resend API key and a verified From address, then send transactional mail over the Resend API.',
    authMode: 'manual_token',
    secretLabel: 'API key',
    secretPlaceholder: 're_…',
    capabilities: ['send_email', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Recipient email(s)',
    settingsFields: [
      {
        key: 'defaultRecipientEmail',
        label: 'Default recipient email(s)',
        placeholder: 'you@domain.com',
        helpText: 'Comma-separated for quick tests.',
      },
      {
        key: 'defaultFromEmail',
        label: 'Verified From email',
        placeholder: 'Prymal <updates@yourdomain.com>',
        requiredOnConnect: true,
        helpText: 'Must be a sender identity permitted by Resend.',
      },
    ],
    integrationRuntime: 'email_provider',
    emailApi: 'resend',
    sortOrder: 11,
  },
  postmark: {
    name: 'Postmark',
    section: 'emails',
    category: 'Transactional',
    color: '#FFD700',
    icon: 'PM',
    description: 'Validate a Postmark Server token and send through Postmark with org-scoped from and recipient defaults.',
    authMode: 'manual_token',
    secretLabel: 'Server API token',
    secretPlaceholder: 'Postmark server token',
    capabilities: ['send_email', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Recipient email(s)',
    settingsFields: [
      {
        key: 'defaultRecipientEmail',
        label: 'Default recipient email(s)',
        placeholder: 'you@domain.com',
      },
      {
        key: 'defaultFromEmail',
        label: 'Verified From address',
        placeholder: 'updates@example.com',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'email_provider',
    emailApi: 'postmark',
    sortOrder: 12,
  },
  sendgrid_mail: {
    name: 'SendGrid',
    section: 'emails',
    category: 'Transactional',
    color: '#1A82E2',
    icon: 'SG',
    description: 'Confirm a SendGrid API key, then send programmatic email with the mail.send scope you grant.',
    authMode: 'manual_token',
    secretLabel: 'API key',
    secretPlaceholder: 'SG.xxx',
    capabilities: ['send_email', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Recipient email(s)',
    settingsFields: [
      {
        key: 'defaultRecipientEmail',
        label: 'Default recipient email(s)',
        placeholder: 'ops@list.com, founder@acme.com',
      },
      {
        key: 'defaultFromEmail',
        label: 'Verified sender email',
        placeholder: 'noreply@yourdomain.com',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'email_provider',
    emailApi: 'sendgrid',
    sortOrder: 13,
  },
  mailgun: {
    name: 'Mailgun',
    section: 'emails',
    category: 'Transactional',
    color: '#F06B66',
    icon: 'MG',
    description: 'Bind Mailgun domain, region, and API key so Prymal can verify credentials and send from your domain.',
    authMode: 'manual_token',
    secretLabel: 'Private API key',
    secretPlaceholder: 'key-…',
    capabilities: ['send_email', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Recipient email(s)',
    settingsFields: [
      {
        key: 'mailgunDomain',
        label: 'Mailgun sending domain',
        placeholder: 'mg.example.com',
        requiredOnConnect: true,
      },
      {
        key: 'mailgunRegion',
        label: 'Mailgun API region',
        input: 'select',
        options: ['us', 'eu'],
        helpText: 'Choose the region of your domain in Mailgun.',
      },
      {
        key: 'defaultRecipientEmail',
        label: 'Default recipient(s)',
        placeholder: 'a@a.com, b@b.com',
      },
      {
        key: 'defaultFromEmail',
        label: 'From email on your domain',
        placeholder: 'notifications@mg.example.com',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'email_provider',
    emailApi: 'mailgun',
    sortOrder: 14,
  },
  brevo: {
    name: 'Brevo',
    section: 'emails',
    category: 'Transactional',
    color: '#0B996E',
    icon: 'BR',
    description: 'Attach a Brevo API key and verified sender so transactional sends exit through Brevo\'s HTTP API.',
    authMode: 'manual_token',
    secretLabel: 'API key',
    secretPlaceholder: 'xkeysib-...',
    capabilities: ['send_email', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Recipient email(s)',
    settingsFields: [
      {
        key: 'defaultRecipientEmail',
        label: 'Default recipient(s)',
        placeholder: 'team@acme.com',
      },
      {
        key: 'defaultFromEmail',
        label: 'Verified sender (Brevo)',
        placeholder: 'newsletter@acme.com',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'email_provider',
    emailApi: 'brevo',
    sortOrder: 16,
  },
  sparkpost: {
    name: 'SparkPost',
    section: 'emails',
    category: 'Transactional',
    color: '#FA6423',
    icon: 'SP',
    description: 'Use a SparkPost API key as the Authorization value and send via the SparkPost transmissions API.',
    authMode: 'manual_token',
    secretLabel: 'API key (Authorization header value)',
    secretPlaceholder: 'Paste the exact key SparkPost provides',
    capabilities: ['send_email', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Recipient email(s)',
    settingsFields: [
      {
        key: 'defaultRecipientEmail',
        label: 'Default recipient(s)',
        placeholder: 'a@a.com, b@b.com',
      },
      {
        key: 'defaultFromEmail',
        label: 'From address (verifed in SparkPost)',
        placeholder: 'notifications@bounces.example.com',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'email_provider',
    emailApi: 'sparkpost',
    sortOrder: 17,
  },
  elastic_email: {
    name: 'Elastic Email',
    section: 'emails',
    category: 'Transactional',
    color: '#00AEEF',
    icon: 'EE',
    description: 'Verify an Elastic Email API key and send transactional messages from a sender you have confirmed.',
    authMode: 'manual_token',
    secretLabel: 'API key',
    secretPlaceholder: 'Elastic Email API key',
    capabilities: ['send_email', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Recipient email(s)',
    settingsFields: [
      {
        key: 'defaultRecipientEmail',
        label: 'Default recipient(s)',
        placeholder: 'team@example.com',
      },
      {
        key: 'defaultFromEmail',
        label: 'Verified sender',
        placeholder: 'updates@yourdomain.com',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'email_provider',
    emailApi: 'elastic_email',
    sortOrder: 18,
  },
  mailjet_email: {
    name: 'Mailjet',
    section: 'emails',
    category: 'Transactional',
    color: '#AA204E',
    icon: 'MJ',
    description: 'Combine Mailjet API key and secret to authenticate REST sends with your chosen From identity.',
    authMode: 'manual_token',
    secretLabel: 'Secret key',
    secretPlaceholder: 'Mailjet secret (private) key',
    capabilities: ['send_email', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Recipient email(s)',
    settingsFields: [
      {
        key: 'mailjetApiKey',
        label: 'Mailjet API key (public)',
        placeholder: 'Your Mailjet API key',
        requiredOnConnect: true,
      },
      {
        key: 'defaultRecipientEmail',
        label: 'Default recipient(s)',
        placeholder: 'hello@example.com',
      },
      {
        key: 'defaultFromEmail',
        label: 'Verified sender',
        placeholder: 'support@domain.com',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'email_provider',
    emailApi: 'mailjet',
    sortOrder: 19,
  },
  sharepoint: {
    name: 'Microsoft SharePoint',
    section: 'files',
    category: 'M365',
    color: '#038387',
    icon: 'MS',
    description: 'Use a Microsoft Graph token with SharePoint/Files access to trust sites and libraries for this org.',
    authMode: 'manual_token',
    secretLabel: 'Microsoft Graph user token (SharePoint/Files scope)',
    secretPlaceholder: 'Microsoft Graph OAuth token for the user who owns the libraries',
    capabilities: ['file_account_link', 'storage_access', 'knowledge_account'],
    supportsPublish: false,
    settingsFields: [],
    integrationRuntime: 'sharepoint_files',
    sortOrder: 24,
  },
  nextcloud: {
    name: 'Nextcloud',
    section: 'files',
    category: 'WebDAV',
    color: '#0082C8',
    icon: 'NC',
    description: 'Verify WebDAV with your Nextcloud base URL, username, and an app password generated for Prymal.',
    authMode: 'manual_token',
    secretLabel: 'App password',
    secretPlaceholder: 'Nextcloud app password',
    capabilities: ['file_account_link', 'storage_access'],
    supportsPublish: false,
    settingsFields: [
      {
        key: 'nextcloudUrl',
        label: 'Nextcloud base URL',
        placeholder: 'https://cloud.example.com',
        requiredOnConnect: true,
        helpText: 'No trailing slash.',
      },
      {
        key: 'nextcloudUsername',
        label: 'Nextcloud login',
        placeholder: 'alice',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'nextcloud_webdav',
    sortOrder: 26,
  },
  webdav: {
    name: 'Generic WebDAV',
    section: 'files',
    category: 'WebDAV',
    color: '#475569',
    icon: 'DV',
    description: 'PROPFIND against any standards-compliant WebDAV URL using Basic auth for generic file storage.',
    authMode: 'manual_token',
    secretLabel: 'Password',
    secretPlaceholder: 'WebDAV password or app password',
    capabilities: ['file_account_link', 'storage_access'],
    supportsPublish: false,
    settingsFields: [
      {
        key: 'webdavUrl',
        label: 'PROPFIND-capable base URL or folder',
        placeholder: 'https://storage.example.com/webdav/Shared',
        requiredOnConnect: true,
      },
      {
        key: 'webdavUsername',
        label: 'Username',
        placeholder: 'svc_prymal',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'webdav_storage',
    sortOrder: 28,
  },
  gitlab_files: {
    name: 'GitLab (files)',
    section: 'files',
    category: 'Code',
    color: '#FC6D26',
    icon: 'GL',
    description: 'Add a personal or project access token so workflows can anchor context on your GitLab host.',
    authMode: 'manual_token',
    secretLabel: 'Personal or project access token',
    secretPlaceholder: 'Token with at least read_api',
    capabilities: ['file_account_link', 'knowledge_account'],
    supportsPublish: false,
    settingsFields: [
      {
        key: 'gitlabHost',
        label: 'GitLab base URL (optional)',
        placeholder: 'https://gitlab.com',
        helpText: 'Defaults to GitLab.com.',
      },
    ],
    integrationRuntime: 'gitlab_pat',
    sortOrder: 31,
  },
  figma_files: {
    name: 'Figma',
    section: 'files',
    category: 'Design',
    color: '#F24E1E',
    icon: 'FG',
    description: 'Paste a Figma personal access token to validate design-account access for file-aware workflows.',
    authMode: 'manual_token',
    secretLabel: 'Personal access token',
    secretPlaceholder: 'Figma PAT',
    capabilities: ['file_account_link'],
    supportsPublish: false,
    settingsFields: [],
    integrationRuntime: 'figma_pat',
    sortOrder: 33,
  },
  bitbucket_files: {
    name: 'Bitbucket Cloud',
    section: 'files',
    category: 'Code',
    color: '#0052CC',
    icon: 'BB',
    description: 'Authenticate with Bitbucket Cloud username plus app password for repos and wiki-backed files.',
    authMode: 'manual_token',
    secretLabel: 'App password',
    secretPlaceholder: 'Bitbucket app password',
    capabilities: ['file_account_link', 'knowledge_account'],
    supportsPublish: false,
    settingsFields: [
      {
        key: 'bitbucketUsername',
        label: 'Bitbucket username',
        placeholder: 'workspace_username',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'bitbucket_basic',
    sortOrder: 35,
  },
  outline: {
    name: 'Outline',
    section: 'knowledge',
    category: 'Wiki',
    color: '#36393F',
    icon: 'OL',
    description: 'Verify an Outline secret key against your team URL so agents can trust that wiki workspace.',
    authMode: 'manual_token',
    secretLabel: 'API key',
    secretPlaceholder: 'Outline secret API key',
    capabilities: ['workspace_account_link', 'knowledge_account'],
    supportsPublish: false,
    settingsFields: [
      {
        key: 'outlineBaseUrl',
        label: 'Outline base URL',
        placeholder: 'https://wiki.acme.com',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'outline_wiki',
    sortOrder: 41,
  },
  confluence: {
    name: 'Confluence Cloud',
    section: 'knowledge',
    category: 'Wiki',
    color: '#0052CC',
    icon: 'CF',
    description: 'Pair your Atlassian site, account email, and API token to validate Confluence Cloud access.',
    authMode: 'manual_token',
    secretLabel: 'Atlassian API token',
    secretPlaceholder: 'Create from id.atlassian.com',
    capabilities: ['workspace_account_link', 'knowledge_account'],
    supportsPublish: false,
    settingsFields: [
      {
        key: 'atlassianSite',
        label: 'Site host (without https)',
        placeholder: 'yourcompany.atlassian.net',
        requiredOnConnect: true,
      },
      {
        key: 'atlassianEmail',
        label: 'Atlassian account email',
        placeholder: 'you@company.com',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'confluence_wiki',
    sortOrder: 42,
  },
  coda: {
    name: 'Coda',
    section: 'knowledge',
    category: 'Docs',
    color: '#F46A54',
    icon: 'CD',
    description: 'Confirm a Coda API token so integrations resolve to the correct workspace and doc permissions.',
    authMode: 'manual_token',
    secretLabel: 'API token',
    secretPlaceholder: 'Coda API token',
    capabilities: ['workspace_account_link', 'knowledge_account'],
    supportsPublish: false,
    settingsFields: [],
    integrationRuntime: 'coda_wiki',
    sortOrder: 43,
  },
  bookstack: {
    name: 'BookStack',
    section: 'knowledge',
    category: 'Wiki',
    color: '#026BC1',
    icon: 'BK',
    description: 'Provide BookStack base URL and token id:secret to validate API access for your internal wiki.',
    authMode: 'manual_token',
    secretLabel: 'API token id:secret',
    secretPlaceholder: '12345:yourLongSecretValue',
    capabilities: ['workspace_account_link', 'knowledge_account'],
    supportsPublish: false,
    settingsFields: [
      {
        key: 'bookstackUrl',
        label: 'BookStack base URL',
        placeholder: 'https://wiki.internal.example.com',
        requiredOnConnect: true,
      },
    ],
    integrationRuntime: 'bookstack_wiki',
    sortOrder: 44,
  },
  knowledge_zapier: {
    name: 'Zapier → knowledge ETL',
    section: 'knowledge',
    category: 'Automation',
    color: '#FF4A00',
    icon: 'KZ',
    description: 'Feed structured Prymal payloads into Zapier so Zaps can land updates in Sheets, Notion, or DBs.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['knowledge_account', 'workspace_account_link', 'autopost'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 45,
  },
  knowledge_make: {
    name: 'Make → knowledge ETL',
    section: 'knowledge',
    category: 'Automation',
    color: '#6D4AFF',
    icon: 'KM',
    description: 'Forward JSON into Make to sync summaries into vector stores, CMS tools, or knowledge bases.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['knowledge_account', 'workspace_account_link', 'autopost'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 46,
  },
  knowledge_n8n: {
    name: 'n8n → knowledge ETL',
    section: 'knowledge',
    category: 'Automation',
    color: '#EA4B71',
    icon: 'KN',
    description: 'Push into n8n webhooks to chain enrichment, chunking, and LORE ingestion automations.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['knowledge_account', 'workspace_account_link', 'autopost'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 47,
  },
  knowledge_ifttt: {
    name: 'IFTTT → knowledge ETL',
    section: 'knowledge',
    category: 'Automation',
    color: '#222222',
    icon: 'KI',
    description: 'Send lightweight payloads through IFTTT for spreadsheet archives or DIY knowledge pipelines.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['knowledge_account', 'workspace_account_link', 'autopost'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 48,
  },
  knowledge_pipedream: {
    name: 'Pipedream → knowledge ETL',
    section: 'knowledge',
    category: 'Automation',
    color: '#208080',
    icon: 'KP',
    description: 'Route drops into Pipedream when you need code transforms before Pinecone, Airtable, or CMS sync.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['knowledge_account', 'workspace_account_link', 'autopost'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 49,
  },
  custom_zapier: {
    name: 'Zapier (custom)',
    section: 'custom',
    category: 'Automation',
    color: '#FF4A00',
    icon: 'CZ',
    description: 'Isolate Zapier Catch Hooks here for billing, alerts, or non-social automations with the same payload shape.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['external_system_sync', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Webhook URL',
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 91,
  },
  custom_make: {
    name: 'Make (custom)',
    section: 'custom',
    category: 'Automation',
    color: '#6D4AFF',
    icon: 'CM',
    description: 'Dedicated Make webhook lane for back-office workflows separate from social automation hooks.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['external_system_sync', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 92,
  },
  custom_n8n: {
    name: 'n8n (custom)',
    section: 'custom',
    category: 'Automation',
    color: '#EA4B71',
    icon: 'CN',
    description: 'Dedicated n8n ingress for on-prem automation fabrics or long-running workflow graphs.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['external_system_sync', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 93,
  },
  custom_ifttt: {
    name: 'IFTTT (custom)',
    section: 'custom',
    category: 'Automation',
    color: '#000000',
    icon: 'CI',
    description: 'Dedicated IFTTT lane for lightweight consumer recipes without mixing traffic with social bridges.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['external_system_sync', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 94,
  },
  custom_pipedream: {
    name: 'Pipedream (custom)',
    section: 'custom',
    category: 'Automation',
    color: '#208080',
    icon: 'CP',
    description: 'Dedicated Pipedream endpoint for code-heavy orchestration away from social fan-out hooks.',
    authMode: 'manual_token',
    secretLabel: 'Bearer (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['external_system_sync', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 95,
  },
  custom_hookdeck: {
    name: 'Hookdeck (custom)',
    section: 'custom',
    category: 'Automation',
    color: '#5C6BF2',
    icon: 'CH',
    description: 'Send Prymal deliveries into Hookdeck for transforms, signatures, and routing before apps consume them.',
    authMode: 'manual_token',
    secretLabel: 'Signing secret (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['external_system_sync', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 96,
  },
  custom_inngest: {
    name: 'Inngest',
    section: 'custom',
    category: 'Automation',
    color: '#5EDD9F',
    icon: 'IN',
    description: 'POST events to Inngest-compatible receivers so durable workflows can react outside Prymal.',
    authMode: 'manual_token',
    secretLabel: 'Signing key (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['external_system_sync', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 97,
  },
  custom_windmill: {
    name: 'Windmill',
    section: 'custom',
    category: 'Automation',
    color: '#3B82F6',
    icon: 'WM',
    description: 'Trigger Windmill scripts or flows through curated webhook URLs with optional bearer headers.',
    authMode: 'manual_token',
    secretLabel: 'Bearer token (optional)',
    secretPlaceholder: 'Optional',
    capabilities: ['external_system_sync', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 98,
  },
  custom_segment_http: {
    name: 'Segment HTTP API',
    section: 'custom',
    category: 'Analytics',
    color: '#43AF79',
    icon: 'SG',
    description: 'Mirror analytics-style payloads toward Segment-compatible HTTP ingestion endpoints.',
    authMode: 'manual_token',
    secretLabel: 'Write key or bearer',
    secretPlaceholder: 'Optional depending on endpoint',
    capabilities: ['external_system_sync', 'autopost'],
    supportsPublish: true,
    settingsFields: [...STANDARD_WEBHOOK_FIELDS],
    integrationRuntime: 'webhook_alias',
    sortOrder: 99,
  },
  custom_webhook: {
    name: 'Custom Webhook',
    section: 'custom',
    category: 'Custom',
    color: '#F97316',
    icon: 'WH',
    description: 'Configure any HTTPS URL plus optional bearer or custom headers for fully bespoke integrations.',
    authMode: 'manual_token',
    secretLabel: 'Bearer token (optional)',
    secretPlaceholder: 'Paste a bearer token if the endpoint requires auth',
    capabilities: ['external_system_sync', 'autopost', 'delivery_feedback'],
    supportsPublish: true,
    targetLabel: 'Endpoint URL',
    settingsFields: [
      {
        key: 'endpointUrl',
        label: 'Endpoint URL',
        placeholder: 'https://example.com/hook',
        requiredOnConnect: true,
      },
      {
        key: 'method',
        label: 'HTTP method',
        input: 'select',
        options: ['POST', 'PUT'],
      },
      {
        key: 'authHeaderName',
        label: 'Auth header name',
        placeholder: 'Authorization',
      },
      {
        key: 'authScheme',
        label: 'Auth scheme',
        input: 'select',
        options: ['Bearer', 'Token', 'Raw'],
      },
    ],
    sortOrder: 90,
  },
};

export function getIntegrationDefinition(service) {
  return INTEGRATION_DEFINITIONS[service] ?? null;
}

export function getTokenStatus(tokenExpiresAt) {
  if (!tokenExpiresAt) return { status: 'unknown', daysRemaining: null };
  const daysRemaining = Math.floor((new Date(tokenExpiresAt) - Date.now()) / (1000 * 60 * 60 * 24));
  if (daysRemaining < 0) return { status: 'expired', daysRemaining: 0 };
  if (daysRemaining <= 7) return { status: 'expiring_soon', daysRemaining };
  return { status: 'valid', daysRemaining };
}

export function isOauthIntegration(service) {
  return getIntegrationDefinition(service)?.authMode === 'oauth';
}

export function isManualIntegration(service) {
  return getIntegrationDefinition(service)?.authMode === 'manual_token';
}

export function getAvailableIntegrations() {
  return Object.entries(INTEGRATION_DEFINITIONS)
    .map(([id, definition]) => serializeAvailableIntegration(id, definition))
    .sort((left, right) => {
      if (left.sortOrder !== right.sortOrder) {
        return left.sortOrder - right.sortOrder;
      }
      return left.name.localeCompare(right.name);
    });
}

export function serializeAvailableIntegration(id, definition = getIntegrationDefinition(id)) {
  if (!definition) {
    return null;
  }

  return {
    id,
    name: definition.name,
    section: definition.section ?? 'custom',
    category: definition.category,
    color: definition.color,
    icon: definition.icon,
    description: definition.description,
    authMode: definition.authMode,
    configured:
      definition.authMode === 'oauth'
        ? hasConfiguredEnvValue(definition.clientId?.()) && hasConfiguredEnvValue(definition.clientSecret?.())
        : true,
    capabilities: definition.capabilities ?? [],
    supportsPublish: Boolean(definition.supportsPublish),
    supportsImagePublish: Boolean(definition.supportsImagePublish),
    targetLabel: definition.targetLabel ?? null,
    secretLabel: definition.secretLabel ?? null,
    secretPlaceholder: definition.secretPlaceholder ?? null,
    settingsFields: definition.settingsFields ?? [],
    sortOrder: definition.sortOrder ?? 100,
  };
}

export function sanitizeIntegrationMeta(service, meta = {}) {
  const definition = getIntegrationDefinition(service);
  const settings = sanitizeIntegrationSettings(service, meta.settings ?? {});
  const linkedInNeedsReconnect = service === 'linkedin' && meta.authMode === 'manual_token';
  const recentDeliveries = Array.isArray(meta.recentDeliveries)
    ? meta.recentDeliveries.slice(0, 8).map((entry) => ({
        service,
        publishedAt: entry.publishedAt ?? null,
        target: entry.target ?? null,
        status: entry.status ?? 'sent',
        providerMessageId: entry.providerMessageId ?? null,
        preview: entry.preview ?? null,
        linkUrl: entry.linkUrl ?? null,
      }))
    : [];

  const profile = meta.profile
    ? {
        name: meta.profile.name ?? null,
        handle: meta.profile.handle ?? null,
        workspace: meta.profile.workspace ?? null,
        avatarUrl: meta.profile.avatarUrl ?? null,
        availableAuthors: Array.isArray(meta.profile.availableAuthors)
          ? meta.profile.availableAuthors
              .slice(0, 30)
              .map((author) => ({
                urn: author.urn ?? null,
                name: author.name ?? author.urn ?? null,
                type: author.type ?? null,
                role: author.role ?? null,
              }))
              .filter((author) => author.urn)
          : [],
        organizations: Array.isArray(meta.profile.organizations)
          ? meta.profile.organizations
              .slice(0, 30)
              .map((organization) => ({
                urn: organization.urn ?? null,
                name: organization.name ?? organization.urn ?? null,
                role: organization.role ?? null,
              }))
              .filter((organization) => organization.urn)
          : [],
      }
    : null;

  return {
    authMode: definition?.authMode ?? 'oauth',
    settings,
    needsReconnect: linkedInNeedsReconnect,
    reconnectMessage: linkedInNeedsReconnect
      ? 'LinkedIn now uses OAuth. Please reconnect LinkedIn to continue publishing.'
      : null,
    health: linkedInNeedsReconnect
      ? {
          status: 'degraded',
          checkedAt: meta.health?.checkedAt ?? null,
          message: 'LinkedIn now uses OAuth. Please reconnect LinkedIn to continue publishing.',
        }
      : meta.health
      ? {
          status: meta.health.status ?? 'unknown',
          checkedAt: meta.health.checkedAt ?? null,
          message: meta.health.message ?? null,
        }
      : null,
    profile,
    publishStats: {
      total: Number(meta.publishStats?.total ?? 0),
      lastPublishedAt: meta.publishStats?.lastPublishedAt ?? null,
      lastTarget: meta.publishStats?.lastTarget ?? null,
    },
    recentDeliveries,
  };
}

export function sanitizeIntegrationSettings(service, rawSettings = {}) {
  const definition = getIntegrationDefinition(service);
  if (!definition) {
    return {};
  }

  const sanitized = {};

  for (const field of definition.settingsFields ?? []) {
    const rawValue = rawSettings[field.key];
    if (rawValue == null) {
      continue;
    }

    if (field.input === 'select') {
      const normalized = String(rawValue).trim();
      if (!normalized) {
        continue;
      }
      if (Array.isArray(field.options) && !field.options.includes(normalized)) {
        continue;
      }
      sanitized[field.key] = normalized;
      continue;
    }

    const normalized = String(rawValue).trim();
    if (!normalized) {
      continue;
    }
    sanitized[field.key] = normalized;
  }

  return sanitized;
}

export function buildDeliveryMeta(service, existingMeta = {}, receipt = {}) {
  const sanitizedMeta = sanitizeIntegrationMeta(service, existingMeta);
  const publishedAt = receipt.publishedAt ?? new Date().toISOString();
  const nextDelivery = {
    publishedAt,
    target: receipt.target ?? null,
    status: receipt.status ?? 'sent',
    providerMessageId: receipt.providerMessageId ?? null,
    preview: receipt.preview ?? null,
    linkUrl: receipt.linkUrl ?? null,
  };

  return {
    ...existingMeta,
    settings: sanitizedMeta.settings,
    health: sanitizedMeta.health,
    profile: sanitizedMeta.profile,
    publishStats: {
      total: Number(sanitizedMeta.publishStats?.total ?? 0) + 1,
      lastPublishedAt: publishedAt,
      lastTarget: receipt.target ?? null,
    },
    recentDeliveries: [nextDelivery, ...(sanitizedMeta.recentDeliveries ?? [])].slice(0, 8),
  };
}
