import {
  siApacheairflow,
  siApachekafka,
  siBluesky,
  siBookstack,
  siBox,
  siBrevo,
  siBitbucket,
  siCoda,
  siConfluence,
  siDiscord,
  siDropbox,
  siElastic,
  siFigma,
  siFiles,
  siGithub,
  siGitlab,
  siGoogleanalytics,
  siGooglechat,
  siGoogledrive,
  siGmail,
  siGuilded,
  siIfttt,
  siJet,
  siJson,
  siLine,
  siMailgun,
  siMailbox,
  siMake,
  siMastodon,
  siMatrix,
  siMattermost,
  siMinutemailer,
  siN8n,
  siNotion,
  siNodedotjs,
  siOutline,
  siResend,
  siRocketdotchat,
  siRss,
  siSocketdotio,
  siSparkpost,
  siTelegram,
  siTemporal,
  siTravisci,
  siWebex,
  siX,
  siZapier,
  siZulip,
  siNextcloud,
} from 'simple-icons';

/** Resolved icon entries from `simple-icons` mapped by integration `service` id. */
export const BRAND_ICONS = {
  gmail: siGmail,
  google_drive: siGoogledrive,
  dropbox: siDropbox,
  box: siBox,
  notion: siNotion,
  discord: siDiscord,
  discord_incoming_webhook: siDiscord,
  telegram: siTelegram,
  x: siX,
  mastodon: siMastodon,
  bluesky: siBluesky,
  github_social: siGithub,
  social_zapier: siZapier,
  knowledge_zapier: siZapier,
  custom_zapier: siZapier,
  social_make: siMake,
  knowledge_make: siMake,
  custom_make: siMake,
  social_ifttt: siIfttt,
  knowledge_ifttt: siIfttt,
  custom_ifttt: siIfttt,
  social_n8n: siN8n,
  knowledge_n8n: siN8n,
  custom_n8n: siN8n,
  social_pipedream: siNodedotjs,
  knowledge_pipedream: siNodedotjs,
  custom_pipedream: siNodedotjs,
  social_hookdeck: siSocketdotio,
  custom_hookdeck: siSocketdotio,
  social_svix: siRss,
  social_paragon: siApacheairflow,
  social_tray: siTravisci,
  social_workato: siApachekafka,
  social_generic_bridge: siJson,
  line_messaging: siLine,
  mattermost_incoming: siMattermost,
  google_chat_incoming: siGooglechat,
  rocket_chat_incoming: siRocketdotchat,
  zulip_incoming: siZulip,
  guilded_webhook: siGuilded,
  matrix_webhook_bridge: siMatrix,
  webex_incoming: siWebex,
  resend: siResend,
  postmark: siMailbox,
  sendgrid_mail: siMinutemailer,
  mailgun: siMailgun,
  brevo: siBrevo,
  sparkpost: siSparkpost,
  elastic_email: siElastic,
  mailjet_email: siJet,
  nextcloud: siNextcloud,
  webdav: siFiles,
  gitlab_files: siGitlab,
  figma_files: siFigma,
  bitbucket_files: siBitbucket,
  outline: siOutline,
  confluence: siConfluence,
  coda: siCoda,
  bookstack: siBookstack,
  custom_inngest: siTemporal,
  custom_windmill: siApacheairflow,
  custom_segment_http: siGoogleanalytics,
};
